version: '3.7' #version du compose

services: #tableau des svc application et DB
  app1: #service name
    build: #
      context: .
    depends_on:
      - mongo
    ports:
    - 8001:3000

  mongo:
    image: mongo:4.0.20
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
    - C:\Users\hp\Documents\WORKSTATION\TUTOS\data:/data/db
    ports:
      - 27019:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9091:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456

