version: '3.7'

services:
  node_app:
    depends_on:
      - postgres_db
    build:
      context: .
    restart: always
    ports:
    - 8001:3000

  postgres_db:
    image: postgres:9.4
    ports:
      - 5433:5432
    restart: always
    environment:
      POSTGRES_USER: devscom
      POSTGRES_PASSWORD: guinee

  pg_admin:
    image: dpage/pgadmin4:4
    ports:
      - 9090:80
    restart: on-failure

