version: '3.7'

services:
  node_app:
    image: mombe090/cloud_native_node_app:0.0.1
    depends_on:
      - mongo
    deploy:
      replicas: 2
    ports:
    - 8000:3000

  mongo:
    image: mongo:4.0.20
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
    - C:\Users\hp\Documents\WORKSTATION\TUTOS\data:/data/db
    ports:
    - 27018:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456

