apiVersion: v1
kind: Service
metadata:
  name: nodeappsvc
  labels:
    app: node-app
spec:
  type: LoadBalancer
  ports:
    - port: 8085
      targetPort: 3000
      protocol: TCP
  selector:
    app: node-app
