apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.labels.app }}
    by: {{ .Values.labels.by }}
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
      by: {{ .Values.labels.by }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
        by: {{ .Values.labels.by }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: {{ .Chart.Name }}-image
