apiVersion: v1
kind: Service
metadata:
  name: expresssvc
  labels:
    app: express
spec:
  selector:
    app: express
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8081
      protocol: TCP
