apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodbexpress
  labels:
    app: express
spec:
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - name: express
          image: mongo-express
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: express
              protocol: TCP
          env:
#            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
#              value: root
#            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
#              value: '123456'
            - name: ME_CONFIG_MONGODB_PORT
              value: '27020'
